"use strict";
var platform_1 = require("./types/platform");
exports.PlatformMiddleware = platform_1.PlatformMiddleware;
var message_1 = require("./types/message");
exports.MessageTypes = message_1.MessageTypes;
var Platforms = require("./platforms");
exports.Platforms = Platforms;
var bot_1 = require("./bot");
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = bot_1.default;
var test_1 = require("./test");
exports.Tester = test_1.default;
